.TH man 7 "18 Dec 2014" "1.0" "fred man page"
.SH NAME
Fred \- Manfred
.SH SYNOPSIS
man fred
.SH DESCRIPTION
Manfred is human.
.SH OPTIONS
Manfred does not take any options. However, you can reverse Manfred and get derfnaM.
.SH SEE ALSO
sassou(7), mxs(7)
.SH BUGS
No Known bugs.
.SH AUTHOR
Manfred Touron <m@42.am> (@moul)
